In [1]:
import pandas as pd

In [2]:
df= pd.read_excel('evade.xlsx', index_col=0)
df

Refund  Marital_Status  Taxable_Income  Evade
Tid                                               
1         1               0          125000      0
2         0               1          100000      0
3         0               0           70000      0
4         1               1          120000      0
5         0               2           95000      1
6         0               1           60000      0
7         1               2          220000      0
8         0               0           85000      1
9         0               1           75000      0
10        0               0           90000      1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10 entries, 1 to 10
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Refund          10 non-null     int64
 1   Marital_Status  10 non-null     int64
 2   Taxable_Income  10 non-null     int64
 3   Evade           10 non-null     int64
dtypes: int64(4)
memory usage: 400.0 bytes


In [4]:
feature = df[['Refund','Marital_Status','Taxable_Income']]
target = df[['Evade']]

In [5]:
#feature
feature

Refund  Marital_Status  Taxable_Income
Tid                                        
1         1               0          125000
2         0               1          100000
3         0               0           70000
4         1               1          120000
5         0               2           95000
6         0               1           60000
7         1               2          220000
8         0               0           85000
9         0               1           75000
10        0               0           90000

In [6]:
target

Evade
Tid       
1        0
2        0
3        0
4        0
5        1
6        0
7        0
8        1
9        0
10       1

In [7]:
from sklearn.naive_bayes import GaussianNB
import numpy as np
from sklearn.utils.validation import column_or_1d

#Create a Gaussian Classfier
model = GaussianNB()

#Train the model using the training sets
model.fit(feature, column_or_1d(target))

GaussianNB()

In [8]:
# Kiểm tra độ chính xác
print("Accuracy: ", model.score(feature,np.array(target))*100,'%')

Accuracy:  100.0 %


In [9]:
class_names = model.classes_
class_names

array([0, 1], dtype=int64)

In [10]:
# X_test = [["No", "Married", 120000], ["No", "Single", 90000]]
X_test = [[0, 1, 120000], [0, 0, 90000]]
y_pred = model.predict(X_test)
y_pred

C:\Program Files\Python39\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0, 1], dtype=int64)

In [11]:
import pickle
# Save to file in the current working directory
pkl_filename = 'pickle_model.pkl'
with open(pkl_filename,'wb') as file:
    pickle.dump(model, file)

In [12]:
with open(pkl_filename,'rb') as file:
    pickle_model = pickle.load(file)

In [13]:
X_test = [[0, 0, 75000]]
y_pred = model.predict(X_test)
y_pred

C:\Program Files\Python39\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([0], dtype=int64)