In [9]:
import numpy as np
import scipy
from scipy.linalg import lu

%config Completer.use_jedi = False

## Bài tập 1: LU Decomposition
- Tạo ma trận A(4x4) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
- Phân tích thành các thành phần P, L, U. In kết quả
- Tái tạo ma trận B từ các thành phần P, L, U. 

In [10]:
# Tạo ma trận A(4,4) với các giá trị ngẫu nhiên từ 1 đến 10


In [11]:
A =np.random.randint(low=1,high=11,size=(4,4))
A

array([[ 8,  6,  3,  9],
       [ 2,  3,  9,  9],
       [ 2, 10,  8,  8],
       [ 1,  9,  2,  5]])

In [12]:
# Phân tích thành các thành phần P, L, U


In [13]:
P,L,U = lu(A)

In [14]:
# In ma trận hoán vị P


In [15]:
P

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])

In [16]:
# In ma trận tam giác dưới L


In [17]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.25      ,  1.        ,  0.        ,  0.        ],
       [ 0.25      ,  0.17647059,  1.        ,  0.        ],
       [ 0.125     ,  0.97058824, -0.77637131,  1.        ]])

In [18]:
# In ma trận tam giác trên U

In [19]:
U

array([[8.        , 6.        , 3.        , 9.        ],
       [0.        , 8.5       , 7.25      , 5.75      ],
       [0.        , 0.        , 6.97058824, 5.73529412],
       [0.        , 0.        , 0.        , 2.74683544]])

In [20]:
# Tái tạo ma trận B từ các thành phần P, L, U


In [22]:
A = P.dot(L).dot(U)

In [23]:
A

array([[ 8.,  6.,  3.,  9.],
       [ 2.,  3.,  9.,  9.],
       [ 2., 10.,  8.,  8.],
       [ 1.,  9.,  2.,  5.]])