In [2]:
import numpy as np
from numpy.linalg import qr

%config Completer.use_jedi = False

## Bài tập 4: QR Decomposition
- Tạo ma trận C(4x5) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
- Phân tích thành các thành phần Q, R. In kết quả
- Tái tạo ma trận D từ các thành phần Q, R. 

In [9]:
# Tạo ma trận C(4,5) với các giá trị ngẫu nhiên từ 5 đến 10


array([[5, 9, 5, 7, 8],
       [7, 6, 7, 5, 9],
       [9, 8, 6, 6, 8],
       [9, 6, 8, 7, 5]])

In [3]:
C =np.random.randint(low=1,high=11,size=(4,5))
C

array([[ 4,  2,  5,  2,  5],
       [ 7,  4,  2,  1,  8],
       [ 6, 10,  7,  1, 10],
       [ 6,  2, 10,  3,  7]])

In [4]:
# Phân rã QR
# C = Q.R
# C là ma trận mxn
# Q là ma trận mxm
# R là ma trận tam giác trên mxn

In [6]:
Q,R = qr(C,'complete')

In [11]:
# Phân tích thành các thành phần Q, R. In kết quả


In [7]:
# In ra ma trận Q
Q

array([[-0.34174306, -0.18500258,  0.16056227, -0.90730672],
       [-0.59805036, -0.2435477 , -0.75020744,  0.14215866],
       [-0.51261459,  0.84539153,  0.14291303,  0.04599251],
       [-0.51261459, -0.43791749,  0.62528747,  0.39302687]])

In [8]:
# In ra ma trận R
R

array([[-11.70469991,  -9.2270627 , -11.61926414,  -3.33199487,
        -15.20756631],
       [  0.        ,   6.23388433,   0.12645746,  -1.08191381,
          2.51509834],
       [  0.        ,   0.        ,   6.55566238,   1.58969254,
          0.60729441],
       [  0.        ,   0.        ,   0.        ,  -0.44738165,
         -0.18815116]])

In [9]:
# Tái tạo ma trận D từ các thành phần Q, R


In [10]:
D=Q.dot(R)
D

array([[ 4.,  2.,  5.,  2.,  5.],
       [ 7.,  4.,  2.,  1.,  8.],
       [ 6., 10.,  7.,  1., 10.],
       [ 6.,  2., 10.,  3.,  7.]])