# Bài tập 2: Ma trận

In [1]:
import numpy as np

## Yêu cầu 1: Tạo ma trận
- Tạo ma trận A: [[2,5,4], [3,6,1]]
- Tạo ma trận B: [[3,2], [1,4], [5,7]]
- Nhân 2 ma trận: C = A.B

In [3]:
# Tạo ma trận A
A = np.array([[2,5,4], [3,6,1]])
A

array([[2, 5, 4],
       [3, 6, 1]])

In [4]:
# Tạo ma trận B
B = np.array([[3,2], [1,4], [5,7]])
B

array([[3, 2],
       [1, 4],
       [5, 7]])

In [5]:
# nhân 2 ma trận
# C = A.B
C=A.dot(B)
C

array([[31, 52],
       [20, 37]])

In [6]:
print('Ma trận A:\n', A)
print('Ma trận B:\n', B)
print('Ma trận C = A.B:\n', C)

Ma trận A:
 [[2 5 4]
 [3 6 1]]
Ma trận B:
 [[3 2]
 [1 4]
 [5 7]]
Ma trận C = A.B:
 [[31 52]
 [20 37]]


## Yêu cầu 2: Nhân ma trận với vector
- Tạo ma trận A: [[2,4,6], [1,3,5], [4,1,2]]
- Tạo vector v: [1,2,3]
- Nhân A với v : c = A.v

In [8]:
# Tạo ma trận A
A=np.array([[2,4,6], [1,3,5], [4,1,2]])
# Tạo vector v
v=np.array([1,2,3])

In [10]:
# c = A.v
c=A.dot(v)
c

array([28, 22, 12])

In [11]:
print('Ma trận A:\n', A)
print('Vector v:\n', v)
print('Vector c = A.v:\n', c)

Ma trận A:
 [[2 4 6]
 [1 3 5]
 [4 1 2]]
Vector v:
 [1 2 3]
Vector c = A.v:
 [28 22 12]


## Yêu cầu 3: Tìm ma trận chuyển vị của ma trận A, với A: [[1,2,3], [4,5,6]]

In [10]:
# ma trận chuyển vị


array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
A = np.array([[1,2,3], [4,5,6]])
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Yêu cầu 4: Tìm ma trận nghịch đảo của ma trận A, với A: [[1,2,3], [4,5,6], [3,2,4]]

In [18]:
from numpy.linalg import inv

In [19]:
# ma trận nghịch đảo


In [25]:
A= np.array([[1,2,3], [4,5,6], [3,2,4]])
B=inv(A)
B

array([[-0.88888889,  0.22222222,  0.33333333],
       [-0.22222222,  0.55555556, -0.66666667],
       [ 0.77777778, -0.44444444,  0.33333333]])