# Bài tập 4: Tìm k người hàng xóm gần nhất (k-nearest neighbors)

In [1]:
import numpy as np
from numpy.linalg import norm
import pandas as pd

%config Completer.use_jedi = False

## Ví dụ: Tính khoảng cách từ vector v đến ma trận A

In [2]:
# đọc tập tin iris.csv
df = pd.read_csv('data/iris.csv')

In [3]:
# tạo ma trận A
A = np.array(df[['sepal_length','sepal_width','petal_length','petal_width']])

In [4]:
A.shape

(150, 4)

In [5]:
A[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
# tạo vector v
v = np.array([5.2,3.2,1.3,0.1])

In [7]:
# tính khoảng cách từ vector v đến ma trận A (khoảng cách của A-v)
A_v = A - v
distances = []
for i in range(A_v.shape[0]):
    distances.append(norm(A_v[i,:])) # norm 2
result = np.array(distances)    

In [8]:
result.shape

(150,)

In [9]:
result[:5]

array([0.34641016, 0.38729833, 0.50990195, 0.64807407, 0.46904158])

## Yêu cầu 1:
- Viết hàm Distance(A, v) để tính khoảng cách từ vector v đến ma trận A
- Hàm trả về vector là các khoảng cách (tính theo norm 2)

In [10]:
def Distance(A, v):
    A_v = A - v
    distances = []
    for i in range(A_v.shape[0]):
        distances.append(norm(A_v[i,:])) # norm 2
    result = np.array(distances) 
    return result
    #pass

In [11]:
# gọi hàm: result = Distance(A, v)

## Yêu cầu 2: Viết hàm KNN(A, v, k=3) truyền vào ma trận A, vector v và số k mặc định là 3
- Hàm gọi đến hàm Distance để tính khoảng cách từ vector v đến ma trận A
- Sau đó tạo ma trận có 2 cột: cột index (bắt đầu từ 0) và cột các khoảng cách
- Sắp xếp ma trận trên tăng dần khoảng cách và chọn ra k phần tử có khoảng cách nhỏ nhất
- Hàm trả về 2 array: index và distance

In [12]:
# ma trận A, vector v, mặc định k=3
def KNN(A, v, k=3):
    distance = Distance(A, v)
    knn=pd.DataFrame(distance, columns =['distance']).sort_values(by='distance').head(k)
    return knn.index, knn.values
    #pass

## Yêu cầu 3: 
- Đọc tập tin iris.csv ra dataframe df
- Từ dataframe df hãy tạo ma trận A với các thuộc tính 'sepal_length','sepal_width','petal_length','petal_width'
- Tạo vector v có các phần tử: 5.2, 3.2, 1.3, 0.1
- Gọi hàm: ind, dis = KNN(A, v, 3)
- In ra ind và dis
- In ra df.iloc[ind] và cho nhận xét

In [13]:
# đọc tập tin iris.csv
df = pd.read_csv('data/iris.csv')

In [14]:
# tạo ma trận A
A = np.array(df[['sepal_length','sepal_width','petal_length','petal_width']])

In [15]:
v =np.array([5.2, 3.2, 1.3, 0.1])


In [16]:
ind,dis = KNN(A, v, 3)

In [17]:
ind

Int64Index([28, 35, 49], dtype='int64')

In [18]:
dis

array([[0.24494897],
       [0.24494897],
       [0.26457513]])

In [19]:
df.iloc[ind]

sepal_length  sepal_width  petal_length  petal_width species
28           5.2          3.4           1.4          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa