In [30]:
import numpy as np
from numpy.linalg import eig
from numpy.linalg import inv

from numpy import diag

%config Completer.use_jedi = False

## Bài tập 1: 
- Tạo ma trận A(4x4) với các giá trị ngẫu nhiên từ 1 đến 10
- Phân tích ma trận A thành eigenvalues và eigenvectors 
- Xác nhận eigenvector đầu tiên theo A.v = lambda.v có bằng nhau?
- Nếu bằng nhau thi tái cấu trúc A từ các eigenvector và eigenvalue

In [17]:
# Tạo ma trận A(4,4) với các giá trị ngẫu nhiên từ 1 đến 10
import random
random.seed(5)


In [18]:

#A =np.random.randint(low=1,high=11,size=(4,4))
A= np.array([[10,  5,  6,  9],
       [ 1,  8,  4,  1],
       [ 3,  2,  6,  8],
       [ 4,  7,  9,  2]])
A

array([[10,  5,  6,  9],
       [ 1,  8,  4,  1],
       [ 3,  2,  6,  8],
       [ 4,  7,  9,  2]])

In [19]:
# Phân tích ma trận A thành eigenvalues và eigenvectors


In [20]:
eigenvalues, eigenvectors =eig(A)

In [21]:
# in eigenvalues


In [22]:
eigenvalues

array([20.61734964, -4.52030498,  4.09781659,  5.80513874])

In [23]:
# in eigenvectors


In [24]:
eigenvectors

array([[ 0.74137195,  0.30950834, -0.33856498,  0.63592262],
       [ 0.23242156, -0.13155338, -0.64034316, -0.72565014],
       [ 0.4337084 ,  0.52915364,  0.67785748,  0.25501218],
       [ 0.45633855, -0.77903449,  0.1258715 , -0.06326995]])

In [25]:
# Xác nhận eigenvector đầu tiên theo dot và theo eigenvalue có bằng nhau?
# xét một giá trị riêng thứ nhất lambda và một vector riêng thứ nhất v
# so sánh A.v = lambda.v 


In [26]:
B = A.dot(eigenvectors[:,0])
B

array([15.28512467,  4.79191661,  8.9419178 ,  9.40849146])

In [27]:
C=eigenvectors[:,0].dot(eigenvalues[0])
C

array([15.28512467,  4.79191661,  8.9419178 ,  9.40849146])

In [28]:
# Tái cấu trúc A từ các eigenvector và eigenvalue 
# A = P.L.P_1


In [31]:
Q = eigenvectors
R = inv(Q)
L = diag(eigenvalues)
A1= Q.dot(L).dot(R)
A1

array([[10.,  5.,  6.,  9.],
       [ 1.,  8.,  4.,  1.],
       [ 3.,  2.,  6.,  8.],
       [ 4.,  7.,  9.,  2.]])