In [4]:
import numpy as np
from numpy.linalg import eig

## Bài tập 2: 
- Tạo ma trận P(4x4) vuông với các giá trị ngẫu nhiên tứ 1 đến 9
- Tạo ma trận đối xứng $ S = P.P^T$
- Tìm eigenvalues và eigenvectors của S

In [6]:
# Tạo ma trận P(4,4) với các giá trị ngẫu nhiên từ 1 đến 9
import random


In [15]:

P =np.random.randint(low=1,high=10,size=(4,4))
P = np.array([[6, 1, 4, 8],
                   [4, 4, 4, 9],
                   [2, 3, 3, 7],
                   [8, 5, 3, 9]])
P

array([[6, 1, 4, 8],
       [4, 4, 4, 9],
       [2, 3, 3, 7],
       [8, 5, 3, 9]])

In [10]:
# Tạo ma trận đối xứng S = P.P^T


In [16]:
S = P.dot(P.T)
S

array([[117, 116,  83, 137],
       [116, 129,  95, 145],
       [ 83,  95,  71, 103],
       [137, 145, 103, 179]])

In [17]:
# Phân tích ma trận S thành eiganvalues và eiganvectors


In [18]:
eigenvalues, eigenvectors =eig(S)

In [19]:
# In eiganvalues


In [20]:
eigenvalues

array([4.76183795e+02, 1.22688915e+01, 7.51442128e+00, 3.28921086e-02])

In [21]:
# In eiganvectors


In [22]:
eigenvectors

array([[ 0.48232289,  0.31899065, -0.81361076,  0.06039149],
       [ 0.51488641, -0.46983607,  0.06804298, -0.71380403],
       [ 0.37274692, -0.62668592,  0.02602716,  0.68384727],
       [ 0.60275729,  0.53363264,  0.57682777,  0.13852647]])