In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import svd

%config Completer.use_jedi = False

## Bài tập 1: 
- Cho tập tin wineQualityReds.csv. Đọc tập tin vào dataframe
- Từ datafarme, sử dụng SVD để phân tích thành các thành phần U,s,VT
- Tái cấu trúc dataframe theo U, s, VT (giữ nguyên tất cả các thành phần)

In [6]:
A = pd.read_csv('data/wineQualityReds.csv')
A.head()

Unnamed: 0  fixed.acidity  volatile.acidity  citric.acid  residual.sugar  \
0           1            7.4              0.70         0.00             1.9   
1           2            7.8              0.88         0.00             2.6   
2           3            7.8              0.76         0.04             2.3   
3           4           11.2              0.28         0.56             1.9   
4           5            7.4              0.70         0.00             1.9   

   chlorides  free.sulfur.dioxide  total.sulfur.dioxide  density    pH  \
0      0.076                 11.0                  34.0   0.9978  3.51   
1      0.098                 25.0                  67.0   0.9968  3.20   
2      0.092                 15.0                  54.0   0.9970  3.26   
3      0.075                 17.0                  60.0   0.9980  3.16   
4      0.076                 11.0                  34.0   0.9978  3.51   

   sulphates  alcohol  quality  
0       0.56      9.4        5  
1       0.68      9.8        5  
2       0.65      9.8        5  
3       0.58      9.8        6  
4       0.56      9.4        5

In [8]:
U, s, VT = svd(A)

In [9]:
U

array([[-7.50039523e-05,  2.11511085e-02, -1.62737281e-02, ...,
        -4.19183662e-02, -4.28553398e-02, -4.06664916e-02],
       [-1.45136431e-04,  4.13529691e-02, -3.18854999e-02, ...,
         3.08274328e-02,  3.67338666e-02,  3.17362130e-02],
       [-1.53367883e-04,  3.27581670e-02, -1.19198468e-02, ...,
         1.85402776e-03, -1.17085954e-02,  2.49335664e-02],
       ...,
       [-4.32095327e-02, -1.45364124e-02, -2.94581908e-02, ...,
         9.95215416e-01, -4.97636777e-03, -3.07016174e-03],
       [-4.32418483e-02, -1.20083543e-02, -3.43398643e-02, ...,
        -4.84233157e-03,  9.92282009e-01, -3.48741751e-03],
       [-4.32612477e-02, -1.49725301e-02,  6.42454559e-03, ...,
        -3.29295127e-03, -3.65850629e-03,  9.91721497e-01]])

In [10]:
s

array([3.69730119e+04, 1.74062846e+03, 3.00449310e+02, 2.43492807e+02,
       5.87699239e+01, 5.35069791e+01, 2.54581156e+01, 1.38419512e+01,
       7.12221305e+00, 5.93752663e+00, 4.01264958e+00, 1.63038234e+00,
       9.42701420e-01])

In [11]:
VT

array([[-9.98918135e-01, -7.54770269e-03, -4.94027530e-04,
        -2.37936942e-04, -2.35701022e-03, -7.89660106e-05,
        -1.54069347e-02, -4.15322178e-02, -9.34125992e-04,
        -3.11564248e-03, -6.05609811e-04, -9.91257035e-03,
        -5.31275620e-03],
       [-4.52781527e-02,  6.30111556e-02,  4.13447635e-03,
         2.43950136e-03,  2.43956081e-02,  7.45200536e-04,
         2.37175300e-01,  9.64376270e-01,  7.36633318e-03,
         2.40434364e-02,  5.22805149e-03,  7.03299408e-02,
         3.84842979e-02],
       [ 7.21150720e-03, -1.43241072e-01, -5.21109001e-03,
        -3.45739886e-03, -4.57445808e-02, -1.33368585e-03,
        -9.33170833e-01,  2.57825964e-01, -1.49479539e-02,
        -5.14076384e-02, -1.17804778e-02, -1.64688497e-01,
        -9.94345808e-02],
       [ 7.66238152e-03, -6.05318624e-01, -2.80467522e-02,
        -2.37650162e-02, -1.34230965e-01, -5.42614630e-03,
         2.68756955e-01,  4.15114000e-02, -5.80431940e-02,
        -1.87627767e-01, -4.08594289e

In [16]:
Sigma = np.zeros((A.shape[0],A.shape[1]))
Sigma[:A.shape[1],:A.shape[1]]= np.diag(s)
Sigma

array([[36973.01188334,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,  1740.6284635 ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,   300.44931041, ...,
            0.        ,     0.        ,     0.        ],
       ...,
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ],
       [    0.        ,     0.        ,     0.        , ...,
            0.        ,     0.        ,     0.        ]])

In [17]:
B= U.dot(Sigma.dot(VT))
B

array([[1.000e+00, 7.400e+00, 7.000e-01, ..., 5.600e-01, 9.400e+00,
        5.000e+00],
       [2.000e+00, 7.800e+00, 8.800e-01, ..., 6.800e-01, 9.800e+00,
        5.000e+00],
       [3.000e+00, 7.800e+00, 7.600e-01, ..., 6.500e-01, 9.800e+00,
        5.000e+00],
       ...,
       [1.597e+03, 6.300e+00, 5.100e-01, ..., 7.500e-01, 1.100e+01,
        6.000e+00],
       [1.598e+03, 5.900e+00, 6.450e-01, ..., 7.100e-01, 1.020e+01,
        5.000e+00],
       [1.599e+03, 6.000e+00, 3.100e-01, ..., 6.600e-01, 1.100e+01,
        6.000e+00]])