In [1]:
import numpy as np
import pandas as pd

## Bài tập 4: Gợi  ý
- Tải dữ liệu digits từ dataset của sklearn
- Từ dữ liệu, sử dụng TruncatedSVD để giảm chiều dữ liệu chỉ còn 10 component
- Cho biết tỷ lệ phần trăm dữ liệu giữ lại được khi rút xuống chỉ còn 10 component

In [2]:
from sklearn import datasets
from scipy.sparse import csr_matrix
from sklearn.decomposition import TruncatedSVD

In [4]:
# Load the data
digits = datasets.load_digits()
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [5]:
digits.data.shape # 1797 dòng và 64 cột

(1797, 64)

In [6]:
# Standardize the feature matrix
X = digits.data

# Make sparse matrix
X_sparse = csr_matrix(X)

In [7]:
X_sparse # xử lý ma trận thưa

<1797x64 sparse matrix of type '<class 'numpy.float64'>'
	with 58736 stored elements in Compressed Sparse Row format>

In [7]:
# Create a TSVD
tsvd = TruncatedSVD(n_components=10)

In [8]:
# Conduct TSVD on sparse matrix
X_sparse_tsvd = tsvd.fit(X_sparse).transform(X_sparse)

In [9]:
print(type(X_sparse_tsvd))

<class 'numpy.ndarray'>


In [10]:
# Show results
print('Original number of features:', X_sparse.shape[1])
print('Reduced number of features:', X_sparse_tsvd.shape[1])

Original number of features: 64
Reduced number of features: 10


In [11]:
print('Original number of samples:', X_sparse.shape[0])
print('Reduced number of samples:', X_sparse_tsvd.shape[0])

Original number of samples: 1797
Reduced number of samples: 1797


In [12]:
X[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [13]:
X_sparse_tsvd[0]

array([45.86127719, -1.19211551, 21.10005944, -9.48896768, 13.04310725,
       -7.01644433, -8.9602799 ,  0.3964152 ,  1.30839901, -1.39055201])

In [14]:
# View Percent Of Variance Explained By New Features
# Sum of 10 components' explained variance ratios
tsvd.explained_variance_ratio_[0:10].sum()

0.7324265081856203

In [15]:
# 73% with 10 components