# Bài tập tuần 2

## Bài tập số 1

In [5]:
# Definition of survey_vector
survey_vector <- c("R", "R", "L", "L", "R", "R", "C", "C")

In [6]:
# Create survey_vector as a factor: survey_factor
survey_factor = as.factor(survey_vector)

In [7]:
# Print survey_factor
print(survey_factor)

[1] R R L L R R C C
Levels: C L R


In [8]:
# Print levels of survey_factor
print(levels(survey_factor))

[1] "C" "L" "R"


In [9]:
# Print nlevels of survey_factor
print(nlevels(survey_factor))

[1] 3


In [10]:
# How many elements of each factor?
table(survey_factor)

survey_factor
C L R 
2 2 4 

## Bài tập số 2

In [28]:
# Create my_vector: 1 up to 10
my_vector = c(1:10)
print(my_vector)

 [1]  1  2  3  4  5  6  7  8  9 10


In [29]:
# Create my_matrix (3x3): 1 up to 9
my_matrix = matrix(c(1:9), nrow=3, ncol=3, byrow=TRUE)
print(my_matrix)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9


In [30]:
# Create my_factor from sizes
sizes <-c("M","S","L","L","M")
my_factor = as.factor(sizes)
print(my_factor)

[1] M S L L M
Levels: L M S


In [31]:
# Construct my_list with the three data structures above
my_list = list(my_vector, my_matrix, my_factor)
print(my_list)

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
[1] M S L L M
Levels: L M S



In [32]:
# Construct my_super_list with the four data structures above
my_super_list = list(my_vector, my_matrix, my_factor, my_list)
print(my_super_list)

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[3]]
[1] M S L L M
Levels: L M S

[[4]]
[[4]][[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[4]][[2]]
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9

[[4]][[3]]
[1] M S L L M
Levels: L M S




In [33]:
# Display structure of my_super_list (Use str())
str(my_super_list)

List of 4
 $ : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
 $ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2
 $ :List of 3
  ..$ : int [1:10] 1 2 3 4 5 6 7 8 9 10
  ..$ : int [1:3, 1:3] 1 4 7 2 5 8 3 6 9
  ..$ : Factor w/ 3 levels "L","M","S": 2 3 1 1 2


In [35]:
# Print my_matrix, sum of my_matrix, sum of even elements in my_matrix
print(my_matrix)
print(sum(my_matrix))
print(sum(my_matrix[my_matrix %% 2 == 0]))

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[1] 45
[1] 20


## Bài tập số 3:

In [63]:


# Function to check if a number is prime
is_prime <- function(n) {
  if (n <= 1) {
    return(FALSE)
  }
  for (i in 2:sqrt(n)) {
    if (n %% i == 0) {
      return(FALSE)
    }
  }
  return(TRUE)
}

# Function to create matrix that contains randomly generated prime number
create_matrix <- function(nrow, ncol) {
    my_matrix <- matrix(NA, nrow = nrow, ncol = ncol)
    for (i in 1:nrow) {
        for (j in 1:ncol) {
            # Gen randomly prime number
            while (TRUE) {
              num <- sample(1:100, 1) 
              if (is_prime(num)) {
                my_matrix[i, j] <- num
                break
              }
            }
        }
    }
    return (my_matrix)
}

# Function to sum diag of matrix
sum_diag <- function(matrix) {
    sum = 0
    for (i in 1:n) {
        sum = sum + matrix[i,i]
    }
    return (sum)
}

In [58]:
# Create my_matrix (4x4): each element is a randomly generated prime number
n = 4
my_matrix <- create_matrix(nrow = n, ncol = n)
print(my_matrix)

     [,1] [,2] [,3] [,4]
[1,]    3   29   79   53
[2,]   29   61   43    5
[3,]   19   83   79   43
[4,]   43   71   97   23


In [62]:
# Sum the elements on the main diagonal of the matrix
sum = sum_diag(my_matrix)
print(sum)
print(sum(diag(my_matrix)))

[1] 166
[1] 166


## Bài tập số 4:

In [65]:
# Create my_array (4, 4, 2): from 2 matrices created by calling function create_matrix (Bai tap so 3)
matrix1 = create_matrix(4, 4)
matrix2 = create_matrix(4, 4)
my_array = array(c(matrix1,matrix2), dim=c(4,4,2))
print(my_array)

, , 1

     [,1] [,2] [,3] [,4]
[1,]   83   97   29   67
[2,]   29   59    5   67
[3,]   83   43   17   67
[4,]   47   59   61   67

, , 2

     [,1] [,2] [,3] [,4]
[1,]   59   19   29   13
[2,]    5   29   97   23
[3,]   53   79   41   67
[4,]   29   13    7   13



In [68]:
# Use apply to calculate the min of the rows across all the matrices.
print(apply(my_array, c(1), min))

[1] 13  5 17  7


In [69]:
# Use apply to calculate the max of the columns across all the matrices.
print(apply(my_array, c(2), max))

[1] 83 97 97 67


In [70]:
# Use apply to calculate the sum of each matrix in my_array
print(apply(my_array, c(3), sum))

[1] 880 576


## Bài tập số 5

In [72]:
# Create title, actors, reviews
title = "The Shining"
actors_vector <- c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson")
reviews_factor <- factor(c("Good", "OK", "Good", "Perfect", "Bad", "Perfect", "Good"),
                  ordered = TRUE, levels = c("Bad", "OK", "Good", "Perfect"))

In [78]:
# Create the list 'shining_list' from 3 vectors above
shining_list = list(title = title, actors = actors_vector, reviews = reviews_factor)
print(shining_list)

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect



In [79]:
# Select the last actor from list: last_actor
last_actor <- shining_list$actors[length(shining_list$actors)]
last_actor

[1] "Barry Nelson"

In [83]:
# Select the second review from list: second_review
second_review <- shining_list$reviews[2]
print(second_review)

[1] OK
Levels: Bad < OK < Good < Perfect


In [84]:
# Add the element 'release_year' = 1980 to shining_list
shining_list$release_year <- 1980

In [86]:
# Add the element 'director' = "Stanley Kubrick" to shining_list
shining_list$director <- "Stanley Kubrick"

In [87]:
# Print list shining_list
print(shining_list)

$title
[1] "The Shining"

$actors
[1] "Jack Nicholson"   "Shelley Duvall"   "Danny Lloyd"      "Scatman Crothers"
[5] "Barry Nelson"    

$reviews
[1] Good    OK      Good    Perfect Bad     Perfect Good   
Levels: Bad < OK < Good < Perfect

$release_year
[1] 1980

$director
[1] "Stanley Kubrick"



In [88]:
# Print the structure of shining_list
str(shining_list)

List of 5
 $ title       : chr "The Shining"
 $ actors      : chr [1:5] "Jack Nicholson" "Shelley Duvall" "Danny Lloyd" "Scatman Crothers" ...
 $ reviews     : Ord.factor w/ 4 levels "Bad"<"OK"<"Good"<..: 3 2 3 4 1 4 3
 $ release_year: num 1980
 $ director    : chr "Stanley Kubrick"


## Bài tập số 6: Hãy thực hiện những yêu cầu sau với R-core dataframe và/ hoặc Tidyverse
1. Cho dữ liệu mtcars cho sẵn trong R datasets. Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
2. Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
3. Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
4. Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct()
5. In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
6. Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
7. Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
8. Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
9. Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất
10. Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?

#### Note: dùng df = cbind(names = rownames(df), df) hoặc rownames_to_column(df, var = "names"): chuyển cột index thành cột "names"

In [105]:
install.packages("tidyverse")
library(tidyverse)


The downloaded binary packages are in
	/var/folders/rr/zczc3rcd5330r_dz7v75lwfm0000gn/T//RtmpwqMfTK/downloaded_packages


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.4
✔ ggplot2   3.4.2     ✔ stringr   1.5.0
✔ lubridate 1.9.2     ✔ tibble    3.2.1
✔ purrr     1.0.1     ✔ tidyr     1.3.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors


In [118]:
# Đọc dữ liệu. Hiển thị thông tin một số dòng đầu của dữ liệu. In thông tin thống kê chung.
data(mtcars)
df <- mtcars
df = cbind(names = rownames(df), df)

In [119]:
head(df)

names             mpg  cyl disp hp  drat wt    qsec  vs am
Mazda RX4         Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1 
Mazda RX4 Wag     Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1 
Datsun 710        Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1 
Hornet 4 Drive    Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0 
Hornet Sportabout Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0 
Valiant           Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0 
                  gear carb
Mazda RX4         4    4   
Mazda RX4 Wag     4    4   
Datsun 710        4    1   
Hornet 4 Drive    3    1   
Hornet Sportabout 3    2   
Valiant           3    1

In [120]:
summary(df)

    names                mpg             cyl             disp      
 Length:32          Min.   :10.40   Min.   :4.000   Min.   : 71.1  
 Class :character   1st Qu.:15.43   1st Qu.:4.000   1st Qu.:120.8  
 Mode  :character   Median :19.20   Median :6.000   Median :196.3  
                    Mean   :20.09   Mean   :6.188   Mean   :230.7  
                    3rd Qu.:22.80   3rd Qu.:8.000   3rd Qu.:326.0  
                    Max.   :33.90   Max.   :8.000   Max.   :472.0  
       hp             drat             wt             qsec      
 Min.   : 52.0   Min.   :2.760   Min.   :1.513   Min.   :14.50  
 1st Qu.: 96.5   1st Qu.:3.080   1st Qu.:2.581   1st Qu.:16.89  
 Median :123.0   Median :3.695   Median :3.325   Median :17.71  
 Mean   :146.7   Mean   :3.597   Mean   :3.217   Mean   :17.85  
 3rd Qu.:180.0   3rd Qu.:3.920   3rd Qu.:3.610   3rd Qu.:18.90  
 Max.   :335.0   Max.   :4.930   Max.   :5.424   Max.   :22.90  
       vs               am              gear            carb      
 M

In [121]:
# 2. Tạo sub_data chỉ có các thông tin mpg, hp, wt, gear
sub_data <- df[, c("mpg", "hp", "wt", "gear")]
head(sub_data)

mpg  hp  wt    gear
Mazda RX4         21.0 110 2.620 4   
Mazda RX4 Wag     21.0 110 2.875 4   
Datsun 710        22.8  93 2.320 4   
Hornet 4 Drive    21.4 110 3.215 3   
Hornet Sportabout 18.7 175 3.440 3   
Valiant           18.1 105 3.460 3

In [122]:
# 3. Tạp cột mới km_per_litre trong sub_data theo công thức: 1 mpg = 0.425 km/l
sub_data$km_per_litre <- sub_data$mpg * 0.425
head(sub_data)

mpg  hp  wt    gear km_per_litre
Mazda RX4         21.0 110 2.620 4    8.9250      
Mazda RX4 Wag     21.0 110 2.875 4    8.9250      
Datsun 710        22.8  93 2.320 4    9.6900      
Hornet 4 Drive    21.4 110 3.215 3    9.0950      
Hornet Sportabout 18.7 175 3.440 3    7.9475      
Valiant           18.1 105 3.460 3    7.6925

In [123]:
# 4. Tạo sub_data_unique lấy từ mtcars nhưng loại bỏ các dòng trùng (dùng distinct()
sub_data_unique <- unique(df)
head(sub_data_unique)
dim(sub_data_unique)

names             mpg  cyl disp hp  drat wt    qsec  vs am
Mazda RX4         Mazda RX4         21.0 6   160  110 3.90 2.620 16.46 0  1 
Mazda RX4 Wag     Mazda RX4 Wag     21.0 6   160  110 3.90 2.875 17.02 0  1 
Datsun 710        Datsun 710        22.8 4   108   93 3.85 2.320 18.61 1  1 
Hornet 4 Drive    Hornet 4 Drive    21.4 6   258  110 3.08 3.215 19.44 1  0 
Hornet Sportabout Hornet Sportabout 18.7 8   360  175 3.15 3.440 17.02 0  0 
Valiant           Valiant           18.1 6   225  105 2.76 3.460 20.22 1  0 
                  gear carb
Mazda RX4         4    4   
Mazda RX4 Wag     4    4   
Datsun 710        4    1   
Hornet 4 Drive    3    1   
Hornet Sportabout 3    2   
Valiant           3    1

[1] 32 12

In [124]:
# 5. In sub_data_unique với giá trị được sắp xếp giảm dần theo mpg, tăng dần theo hp
sub_data_unique <- sub_data_unique[order(-sub_data_unique$mpg, sub_data_unique$hp), ]
print(sub_data_unique)

                                  names  mpg cyl  disp  hp drat    wt  qsec vs
Toyota Corolla           Toyota Corolla 33.9   4  71.1  65 4.22 1.835 19.90  1
Fiat 128                       Fiat 128 32.4   4  78.7  66 4.08 2.200 19.47  1
Honda Civic                 Honda Civic 30.4   4  75.7  52 4.93 1.615 18.52  1
Lotus Europa               Lotus Europa 30.4   4  95.1 113 3.77 1.513 16.90  1
Fiat X1-9                     Fiat X1-9 27.3   4  79.0  66 4.08 1.935 18.90  1
Porsche 914-2             Porsche 914-2 26.0   4 120.3  91 4.43 2.140 16.70  0
Merc 240D                     Merc 240D 24.4   4 146.7  62 3.69 3.190 20.00  1
Datsun 710                   Datsun 710 22.8   4 108.0  93 3.85 2.320 18.61  1
Merc 230                       Merc 230 22.8   4 140.8  95 3.92 3.150 22.90  1
Toyota Corona             Toyota Corona 21.5   4 120.1  97 3.70 2.465 20.01  1
Volvo 142E                   Volvo 142E 21.4   4 121.0 109 4.11 2.780 18.60  1
Hornet 4 Drive           Hornet 4 Drive 21.4   6 258

In [130]:
# 6. Lọc các xe mà trong tên xe có 'Mazda' trong sub_data_unique. Có bao nhiêu xe thỏa điều kiện này?
mazda_cars <- sub_data_unique %>% filter(str_detect(names, "Mazda"))
cat("Số lượng xe thỏa điều kiện:", nrow(mazda_cars), "\n")

Số lượng xe thỏa điều kiện: 2 


In [131]:
#7. Trong sub_data_unique, cho biết giá trị mpg lớn nhất? Có những dòng dữ liệu nào có mpg = mpg lớn nhất, in kết quả.
max_mpg_value <- max(sub_data_unique$mpg)
max_mpg_rows <- sub_data_unique[sub_data_unique$mpg == max_mpg_value, ]
cat("Giá trị mpg lớn nhất:", max_mpg_value, "\n")
print("Các dòng dữ liệu có mpg = mpg lớn nhất:")
print(max_mpg_rows)

Giá trị mpg lớn nhất: 33.9 
[1] "Các dòng dữ liệu có mpg = mpg lớn nhất:"
                        names  mpg cyl disp hp drat    wt qsec vs am gear carb
Toyota Corolla Toyota Corolla 33.9   4 71.1 65 4.22 1.835 19.9  1  1    4    1


In [132]:
# 8. Lọc các dữ liệu thỏa các điểu kiện sau: mpg >= 25 và cyl=4 và gear=4
filtered_data <- sub_data_unique[sub_data_unique$mpg >= 25 & sub_data_unique$cyl == 4 & sub_data_unique$gear == 4, ]
filtered_data

names          mpg  cyl disp hp drat wt    qsec  vs am gear carb
Toyota Corolla Toyota Corolla 33.9 4   71.1 65 4.22 1.835 19.90 1  1  4    1   
Fiat 128       Fiat 128       32.4 4   78.7 66 4.08 2.200 19.47 1  1  4    1   
Honda Civic    Honda Civic    30.4 4   75.7 52 4.93 1.615 18.52 1  1  4    2   
Fiat X1-9      Fiat X1-9      27.3 4   79.0 66 4.08 1.935 18.90 1  1  4    1

In [133]:
# 9. Thực hiện việc thống kê theo cyl, từ đó cho biết số lượng từng nhóm, cyl, hp lớn nhất, mpg nhỏ nhất

# Group by 'cyl' and calculate statistics for 'hp' and 'mpg'
cyl_summary <- sub_data_unique %>%
  group_by(cyl) %>%
  summarise(
    count = n(),
    max_hp = max(hp),
    min_mpg = min(mpg)
  )

# Print the summary
print(cyl_summary)

# A tibble: 3 × 4
    cyl count max_hp min_mpg
  <dbl> <int>  <dbl>   <dbl>
1     4    11    113    21.4
2     6     7    175    17.8
3     8    14    335    10.4


In [134]:
# 10. Trong sub_data, cho biết xe nào có km_per_litre lớn nhất, nhỏ nhất?
max_km_car <- sub_data %>%
  filter(km_per_litre == max(km_per_litre))
min_km_car <- sub_data %>%
  filter(km_per_litre == min(km_per_litre))
print("Xe có km_per_litre lớn nhất:")
print(max_km_car)
print("Xe có km_per_litre nhỏ nhất:")
print(min_km_car)

[1] "Xe có km_per_litre lớn nhất:"
                mpg hp    wt gear km_per_litre
Toyota Corolla 33.9 65 1.835    4      14.4075
[1] "Xe có km_per_litre nhỏ nhất:"
                     mpg  hp    wt gear km_per_litre
Cadillac Fleetwood  10.4 205 5.250    3         4.42
Lincoln Continental 10.4 215 5.424    3         4.42
